baseURL = "/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
title = "Robo Kiwi"
disqusShortname = "robokiwi"
pluralizeListTitles = false
disableAliases = false
enableGitInfo = true
paginate =  20

[outputs]
home = [ "HTML", "RSS"]
section = [ "HTML", "RSS"]
page = ["HTML"]

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"

[permalinks]
  posts = '/:year/:month/:day/:title/'

[social]
twitter = "whup"

[params]
flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"
enableComments = false

[markup]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = "solarized-light"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.global]]
name = "Blog"
weight = 1
identifier = "blog"
url = "/blog/"

[[menu.global]]
name = "Wiki"
weight = 5
identifier = "wiki"
url = "/wiki/"

[[menu.external]]
name = "GitHub"
weight = 200
icon = true
identifier = "github"
post = "external"
url = "https://github.com/davidmoore/"

[frontmatter]
  date = ['date', 'publishDate', 'lastmod', ':git']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[module]
[[module.mounts]]
  source = 'src/css'
  target = 'assets/css'